### ISSUE TITLE
!!!  Chat for Oct 23 - Oct 31

### ISSUE THREAD

**Issue by NotNemesis** [NotNemesis/Turing#35]
Chat here, ask me questions, talk to each other and what not.

**Comment by MC47** [comment]
Hi wiki life is kinda irritating

**Comment by NotNemesis** [comment]
ikr no customization whatsoever

**Comment by MC47** [comment]
I will be adding some images and maybe try to find some tables/templates.

**Comment by MC47** [comment]
I hope I won't have to steal from other wikis

**Comment by NotNemesis** [comment]
haha you can if you want

**Comment by MC47** [comment]
Well some wiki codes aren't universal. E.g. Mario Wikipedia's coding isn't compatible with other Wikis

**Comment by MC47** [comment]
And we lost the main coder of the PG3D wiki: Bashihbk01

**Comment by NotNemesis** [comment]
:cry:

**Comment by NotNemesis** [comment]
I will post up some repo rules later today regarding making commits and whatnot

**Comment by sonason** [comment]
Hey guys! I'm finally on!

**Comment by NotNemesis** [comment]
good, i'll add those options that you made in a few minutes

**Comment by sonason** [comment]
Thanks!

**Comment by NotNemesis** [comment]
Added rules doc because I promised earlier
<a href="https://github.com/NotNemesis/Turing/blob/master/rules.md">Here are da rulez</a>
If you have any suggestions for new rules, please say so!

**Comment by sonason** [comment]
Can someone plz tell me how to make a new branch?

**Comment by NotNemesis** [comment]
when you make a commit, at the bottom of the screen, it has an opiton to either commit to master or make a new branch and commit there. Select the second option, name your branch, and commit!

**Comment by NotNemesis** [comment]
http://prntscr.com/8uzv82 for picture of where it is

**Comment by sonason** [comment]
Okay, I just posted unfinished code for MSTE

**Comment by NotNemesis** [comment]
merged @sonason  :smirk: 

Just to remind that whenever you add something, I will merge it within 24hours. During that time, you can keep adding things to that branch.

**Comment by sonason** [comment]
New code for MSTE

**Comment by NotNemesis** [comment]
received and synced, will delete that branch now

**Comment by NotNemesis** [comment]
lots o changes today. be sure to read the rules over as i added clarification :sunglasses:

**Comment by sonason** [comment]
thanks

**Comment by NotNemesis** [comment]
would you like me to merge #63 now?

**Comment by sonason** [comment]
Happy Hallowe'en everyone!

**Comment by NotNemesis** [comment]
Closing chat and happy halloween :skull: :ghost:
